#!/bin/bash
for((i=0; i<10; i++)); do
    echo "i = $i"
    echo "------------"
    for((j=0; j<5; j++)); do
        if [ $i -gt 2 ] && [ $i -lt 8 ]
        then
            continue 2
        fi
        echo "j = $j"
    done
    
    
done > output.txt
